# Generated by Django 5.0.1 on 2024-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('Budget', models.IntegerField()),
                ('manager_email', models.EmailField(max_length=254)),
                ('managed_by', models.CharField(max_length=100)),
                ('Attendee', models.IntegerField(default=0)),
                ('created_by', models.EmailField(max_length=254)),
            ],
            options={
                'permissions': (('can_edit_event', 'To edit Event'), ('can_add_event', 'To add Event')),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('maneged_by', models.CharField(max_length=100)),
                ('Budget', models.IntegerField()),
            ],
        ),
    ]
